### ISSUE TITLE
Switch to 4Byte for signature lookups

### ISSUE THREAD

**Issue by volsa** [brumewallet/wallet#13]
Hi, [Etherface](https://github.com/volsa/etherface) author here 👋
Just wanted to let you know I'll be retiring Etherface, meaning the REST API will probably be down at the end of the month.
I'm in the process of feeding all crawled function, event and error signatures into 4Byte, meaning any signature you've found on Etherface should shortly also be available there.

**Comment by hazae41** [comment]
Thanks for letting us know

Is it end of November or end of December?

Unfortunately 4Bytes blocks Tor :(

**Comment by hazae41** [comment]
Good news, OpenChain doesn't block Tor! 

Maybe you should also mirror Etherface there? 

Thanks

**Comment by volsa** [comment]
I'll add some links in the README for alternatives, but the REST API will be down. FYI here's also an interesting alternative https://sig.api.vechain.energy/

**Comment by hazae41** [comment]
Hey, I just wanted to let you know I made my own alternative that is fully decentralized

https://sighash.hazae41.me
