### ISSUE TITLE
Nothing happens when trying to add new wallet on Safari

### ISSUE THREAD

**Issue by czepluch** [brumewallet/wallet#16]
Downloaded the Brume Wallet ios app and went to the wallet website in safari. Generated an account, but when I try to add a wallet nothing happens. I can type in a name for the wallet and successfully generate the private key. But when I try to "Add with authentication" or "Add without authentication" nothing happens. So I am stuck at creating a wallet.

**Comment by hazae41** [comment]
- Did you try to reload the page? 
- Did you try turning the extension off-then-on? 
- Which version does TestFlight display?

**Comment by czepluch** [comment]
Alright. Just tried unintalling and reinstalling the app through testflight and now it seems to work!
Great onboarding experience btw now that it works :)
