### ISSUE TITLE
Brume extension blocks dappnode

### ISSUE THREAD

**Issue by czepluch** [brumewallet/wallet#17]
Another thing I noticed after trying out the Brume Wallet extension for Firefox is that I can no longer access the Dappnode UI via "my.dappnode". I just get this weird message as if the extension somehow tries to open the url instead. 
<img width="744" alt="Screenshot 2024-02-27 at 19 35 15" src="https://github.com/brumewallet/wallet/assets/1026799/97a84af5-c160-4cc1-9522-c8fcead2590b">
and
<img width="979" alt="Screenshot 2024-02-27 at 19 36 28" src="https://github.com/brumewallet/wallet/assets/1026799/e4ff45b2-eef2-4baf-bd7f-ecf71ba1c0cf">

**Comment by hazae41** [comment]
Partially fixed; the extension may not work on that url, but at least it should be unblocked

**Comment by hazae41** [comment]
Can you please test if "my.dappnode" works on Chrome or Safari?

**Comment by hazae41** [comment]
And also, can you test if adding `browser.fixup.domainsuffixwhitelist.dappnode` to `true` into Firefox's `about:config` fixes the issue?

https://github.com/noraj/the-hacking-trove/blob/master/docs/Cheat%20Sheets/custom_TLDs.md
