### ISSUE TITLE
Custom RPC support

### ISSUE THREAD

**Issue by taxmeifyoucan** [brumewallet/wallet#20]
From what I can tell, the wallet supports only a couple of [hardcoded](https://github.com/brumewallet/wallet/blob/f5ddeaf7d56a36bf041a2086af69e2ec4bffa11a/src/libs/ethereum/mods/chain.tsx#L19) rpc providers and it doesn't allow users to input their own rpc address. This is a crucial feature in privacy wallet. Even if requests are torified, using trusted third party is inferior to your own node. The only current solution is compile it with own address added to the code which is not very practical

**Comment by hazae41** [comment]
Not an issue, please propose ideas on other channels

**Comment by taxmeifyoucan** [comment]
@hazae41 Very disappointing. First of all, this is an issue. Your 'privacy' wallet is just a larp unless you allow users to customize RPC. Missing a basic feature for trustless operation = a serious issue. 

I can see you find this as more of a feature request, in that case a suggest you add flag to label this issue as 'feature request' which is a regular way of tracking requested features in public github repo. In case you are choosing other project management with less transparency, please point me to right channel instead of just closing it.

**Comment by hazae41** [comment]
You can discuss such things on Twitter, Discord, SimpleX

All links there

https://brume.money

https://hazae41.me
