### ISSUE TITLE
Broken on Defillama

### ISSUE THREAD

**Issue by extemporary** [brumewallet/wallet#23]
The wallet seems to not work on [Defillama's swap](https://swap.defillama.org), the biggest aggregator on Ethereum. There is no Brume wallet connect option, only Metamask and the other usual options. If this is an issue with the app itself, maybe you can notify [0xngmi, its maintainer, on Twitter](https://x.com/0xngmi)?

**Comment by hazae41** [comment]
Did you try clicking on MetaMask?

**Comment by hazae41** [comment]
I can't do anything about it, if you see an app that doesn't display Brume you can pressure the admin to support EIP-6963
