### ISSUE TITLE
Adding Custom Token Errors Out

### ISSUE THREAD

**Issue by extemporary** [brumewallet/wallet#24]
Trying to add a custom new token causes the wallet to error out with `{"name":"i","message":"No Promise in Promise.any was resolved"}`
or `{"code":-32603,"message":"No Promise in Promise.any was resolved"}` after about a minute of nothing happening. The token never gets added. This happens regardless of the token being added.

Browser: Firefox (both Standard and Strict privacy settings)
Version: 0.6.524

**Comment by hazae41** [comment]
Did you try on another device or network? This is likely a connection issue

**Comment by hazae41** [comment]
Ok I will try thanks

**Comment by hazae41** [comment]
It works for me, please tell me which token you tried

**Comment by hazae41** [comment]
Please tell me one

**Comment by hazae41** [comment]
I just checked and it only errors when Tor is starting
