### ISSUE TITLE
Debugging experience: how to list all network calls?

### ISSUE THREAD

**Issue by paulmillr** [brumewallet/wallet#25]
As a user, I want to check which requests Brume is making. How do I do this in Chrome-like browser?

When I "inspect" extension's service_worker and offline.html, "network" inspector only shows requests to `data:application/wasm;base64...`. I don't see any real network requests there.

**Comment by hazae41** [comment]
Can't be done for now, planned, please use issues for real issues (bugs, vulns) not virtual issues (features), thanks :)
