### ISSUE TITLE
readme: remove cryptography sentence, or clarify it

### ISSUE THREAD

**Issue by paulmillr** [brumewallet/wallet#29]
https://github.com/brumewallet/wallet?tab=readme-ov-file#supply-chain-hardened

>All JavaScript cryptography packages are from [Paul Miller](https://github.com/paulmillr) and are audited

I don't see any js cryptography used in the code, it's all wasm. There is one place where `noble/curves` are used for `getPublicKey`, which is not relevant.

Unless i'm missing something, the section should be removed from README, to be correct.

**Comment by hazae41** [comment]
We still use BIP32, BIP39, QR

```
    "@paulmillr/qr": "^0.2.0",
    "@scure/bip32": "^1.5.0",
    "@scure/bip39": "^1.4.0",
```

This was mostly to explain we don't use shitty unaudited JS libraries 

I can remove it since we mainly use WASM now

**Comment by paulmillr** [comment]
qr is not audited, and scure is not cryptography.

**Comment by hazae41** [comment]
Done
