### ISSUE TITLE
Remove DependencyInfoBlock for F-Droid

### ISSUE THREAD

**Issue by linsui** [brumewallet/wallet#35]
We find that there is a `DependencyInfoBlock` in your apk. It's a [Frosting](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) block in the signing block. It's added by AGP and signed by Google's public key so it can't be read by anyone else except Google.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Comment by hazae41** [comment]
Sure thank you for noticing

**Comment by hazae41** [comment]
Ok so this is for security? As this block can contain malicious code if our supply-chain is compromised, is this correct?

**Comment by linsui** [comment]
Thanks! There are some more info in https://gitlab.com/fdroid/fdroidserver/-/issues/1056.
